version: 2.1
executors:
  paro-frontend-build:
jobs:
  build:
#    executor: paro-frontend-build
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: git checkout develop
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: cd ./app && npm install && npm run build
      - save_cache:
          key: npm-cache{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: git checkout develop
      - run: cd ./app && npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
        image: ubuntu-2004:202010-01  
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: git checkout develop
      - run: aws s3 sync ./app/build s3://ci-cd-example1
    

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          filters:
             branches:
               only:
                 - develop
#          context: myfreeawsaccess
          requires:
            - build
      - deploy:
          requires:
            - test

